version: '3.1'
services:
  db:
    image: mysql:latest
    restart: always
    environment:

      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: integrador2
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"